/*
import "@/styles/globals.css"

import type { Metadata } from "next"

import GeneratorNavbar from "@/components/GeneratorNavbar"
import Providers from "@/components/Providers"
import SelectTemplateSidebar from "@/components/Sidebar/SelectTemplate"
import { poppins } from "@/styles/fonts"

export const metadata: Metadata = {
  title: {
    default: "ReadME Generator  ",
    template: "ReadME Generator | %s ",
  },
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`bg-background min-h-screen min-w-screen ${poppins.className} text-secondary`}
      >
        <Providers>
          <GeneratorNavbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}

*/
